name: money_manager
description: تطبيق إدارة الأموال الشخصية
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # قاعدة البيانات
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # إدارة الحالة
  provider: ^6.1.1
  
  # التنسيق والواجهات
  intl: 0.20.2
  flutter_svg: ^2.0.9
  
  # الرسوم البيانية
  fl_chart: ^0.66.2
  
  # التقويم
  table_calendar: ^3.0.9
  
  # الإشعارات
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  
  # التصدير والمشاركة
  pdf: ^3.10.7
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  
  # الأيقونات
  cupertino_icons: ^1.0.6
  
  # Google Fonts للخطوط
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # إضافة الخطوط
